# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portly < Formula
  desc "CLI for managing ports — list, inspect, and kill by port number"
  homepage "https://github.com/mohokh67/portly"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.2/portly_0.2.2_darwin_amd64.tar.gz"
      sha256 "4887ae2041fabf2f7a40e93c4a65d5dea50c9c9f95a06b18ba84610502e95651"

      define_method(:install) do
        bin.install "portly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.2/portly_0.2.2_darwin_arm64.tar.gz"
      sha256 "5e72d21b38113a324a626d8959b78ca91486f9d7594b8a1d825284808dd78711"

      define_method(:install) do
        bin.install "portly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.2/portly_0.2.2_linux_amd64.tar.gz"
      sha256 "8213a2313714b43cbdc3fd2895bbe6daa5e554cade4ce4405ffde3874add2917"
      define_method(:install) do
        bin.install "portly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.2/portly_0.2.2_linux_arm64.tar.gz"
      sha256 "d405a161dfbb950da6d8dcd36ed306cf5b450cc6bf7c54f3603d7a72abcfaeec"
      define_method(:install) do
        bin.install "portly"
      end
    end
  end

  test do
    system "#{bin}/portly", "--version"
  end
end
