# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portly < Formula
  desc "CLI for managing ports — list, inspect, and kill by port number"
  homepage "https://github.com/mohokh67/portly"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.1/portly_0.2.1_darwin_amd64.tar.gz"
      sha256 "126953782b550c61b509a5a74c3dd744624c57bb26e34591a01ab05afd76d3f6"

      define_method(:install) do
        bin.install "portly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.1/portly_0.2.1_darwin_arm64.tar.gz"
      sha256 "028a77be2d0b15f077825c7b1add556e49d62cece13fbe5fa69e12f94d2db28c"

      define_method(:install) do
        bin.install "portly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.1/portly_0.2.1_linux_amd64.tar.gz"
      sha256 "98c1e737e5c913273844145bbc3a5446963602c79d9faecc7ebd7fdaa8e455a3"
      define_method(:install) do
        bin.install "portly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohokh67/portly/releases/download/v0.2.1/portly_0.2.1_linux_arm64.tar.gz"
      sha256 "ee4346c73e27a473cf1ffa64d4f797342e3fe42ae152908d57702275d1d786a8"
      define_method(:install) do
        bin.install "portly"
      end
    end
  end

  test do
    system "#{bin}/portly", "--version"
  end
end
