# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portly < Formula
  desc "CLI for managing ports — list, inspect, and kill by port number"
  homepage "https://github.com/mohokh67/portly"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohokh67/portly/releases/download/v0.1.2/portly_0.1.2_darwin_amd64.tar.gz"
      sha256 "92e367de1fb2c5415fd4c6c5afade6c946bd83968d0f59de2740b7ee02d5174d"

      define_method(:install) do
        bin.install "portly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohokh67/portly/releases/download/v0.1.2/portly_0.1.2_darwin_arm64.tar.gz"
      sha256 "1bacc239d72b4f1236c59c55ee7cccda8c830c74d2dd91af0ed5d01c8a4f04ba"

      define_method(:install) do
        bin.install "portly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohokh67/portly/releases/download/v0.1.2/portly_0.1.2_linux_amd64.tar.gz"
      sha256 "0026dc44fcbbe7ab86d56ebb7e5ac38607402ee38a2f7509a4d5caf28e24b14b"
      define_method(:install) do
        bin.install "portly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohokh67/portly/releases/download/v0.1.2/portly_0.1.2_linux_arm64.tar.gz"
      sha256 "351650a9b1b7b6e295fc9a047f0c2ccaf867005badf0cb29fbccd75c50ad1573"
      define_method(:install) do
        bin.install "portly"
      end
    end
  end

  test do
    system "#{bin}/portly", "--version"
  end
end
